watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: 'komorebic start --whkd'
  stop_command: 'komorebic stop --whkd'
  reload_command: 'komorebic reload-configuration'
bars:
  status-bar:
    enabled: true
    screens: ['*']
    class_name: 'yasb-bar'
    alignment:
      position: 'top'
      center: false
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: '100%'
      height: 30
    widgets:
      left: ['home', 'active_window']
      center: []
      right: ['media', 'volume', 'weather', 'clock']
widgets:
  media:
    type: 'yasb.media.MediaWidget'
    options:
      label: '{title} - {artist}'
      show_thumbnail: true
      controls_left: true
      hide_empty: true
      controls_only: false
      callbacks:
        on_left: 'toggle_media_menu'
        on_middle: 'toggle_media_menu'
        on_right: 'toggle_media_menu'
      scrolling_label:
        enabled: true
        update_interval_ms: 33
        style: 'left'
        separator: ' | '
        label_padding: 1
        ease_slope: 20
        ease_pos: 0.8
        ease_min: 0.5
      icons:
        play: "\uf04b"
        pause: "\uf04c"
        prev_track: "\uf048"
        next_track: "\uf051"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: 'normal'
        border_color: 'System'
        alignment: 'right'
        direction: 'down'
        thumbnail_size: 120
      media_menu_icons:
        play: "\uf04b"
        pause: "\uf04c"
        prev_track: "\uf048"
        next_track: "\uf051"
      label_shadow:
        enabled: true
        color: 'black'
        radius: 3
        offset: [1, 1]
  active_window:
    type: 'yasb.active_window.ActiveWindowWidget'
    options:
      label: '{win[title]}'
      label_alt: '{win[process][name]}'
      label_no_window: ''
      label_icon: false
      label_icon_size: 14
      max_length: 56
      max_length_ellipsis: '...'
      monitor_exclusive: true
  clock:
    type: 'yasb.clock.ClockWidget'
    options:
      label: '{%a %d %b  %H:%M}'
      locale: 'pt_BR'
      timezones: []
      #timezones: ["America/Montreal"]
      callbacks:
        on_right: 'toggle_calendar'
      calendar:
        blur: True
        round_corners: True
        round_corners_type: 'normal'
        border_color: 'System'
        alignment: 'center'
        direction: 'down'
  weather:
    type: 'yasb.weather.WeatherWidget'
    options:
      callbacks:
        on_left: 'toggle_card'
      label: '<span>{icon}</span> {temp}'
      label_alt: '{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}'
      api_key: '445eb3da94c348dfab9221737252707' # Get your free API key from https://www.weatherapi.com/
      update_interval: 600 # Update interval in seconds, Min 600 seconds
      hide_decimal: true
      location: 'Jaú'
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyIcyDay: "\udb81\udd98"
        snowyIcyNight: "\udb81\udd98"
        blizzardDay: "\uebaa"
        default: "\uebaa"
  volume:
    type: 'yasb.volume.VolumeWidget'
    options:
      label: '{icon}'
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      callbacks:
        on_left: 'toggle_volume_menu'
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: 'rounded'
        alignment: 'center'
        direction: 'down'
      animation:
        enabled: true
        type: 'fade'
        duration: 100
  home:
    type: 'yasb.home.HomeWidget'
    options:
      label: "\ue62a"
      menu_list:
        - { title: 'User Home', path: '~' }
        - { title: 'Download', path: "~\\Downloads" }
        - { title: 'Documents', path: "~\\Documents" }
        - { title: 'Pictures', path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      border_color: 'System'
      round_corners_type: 'normal'
      container_padding:
        top: 0
        left: 6
        bottom: 0
        right: 12
